name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for building multi-platform images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (you need to set DockerHub credentials as GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.sahil4353  }}
          password: ${{ secrets.sahil4353 }}

      # Step 4: Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: YOUR_DOCKER_USERNAME/docker-react-mysql:latest

